### PR TITLE
Added Sanctum Support

### PR DESCRIPTION
**Pull request by farazappy**

### CODE REVIEW

**Comment by radudiaconu0** [comment]
some update on this? i should need this ;)

**Comment by ricardogobbosouza** [comment]
Added support @nuxtjs/auth v5

**Comment by radudiaconu0** [comment]
ok.....but for pusher the authorizer is needed and the current implementation doesnt have it

**Comment by ricardogobbosouza** [comment]
I will think of a better implement for this

**Comment by ricardogobbosouza** [comment]
https://github.com/nuxt-community/laravel-echo/issues/45

**Pull request closed without merging**
